# This is an example that uses the Dockerfile in this directory.
# You can pull a pre-built version by changing the
#
# build: . 
#
# to
#
# image: bradleybossard/docker-adminer
adminer:
  build: .
  environment:
    - VIRTUAL_HOST=adminer.goliath.bradleybossard.com  
  ports:
   - "8091:80"
  links:
    - db

db:
  image: mongo
  ports:
   - "27020:27017"
